-- Copyright (C) 2012-2015 Laurent Zubiaur - voodoocactus.com
--
-- Permission is hereby granted, free of charge, to any person obtaining a copy
-- of this software and associated documentation files (the "Software"), to deal
-- in the Software without restriction, including without limitation the rights
-- to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
-- copies of the Software, and to permit persons to whom the Software is
-- furnished to do so, subject to the following conditions:
--
-- The above copyright notice and this permission notice shall be included in
-- all copies or substantial portions of the Software.
--
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
-- IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
-- FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
-- AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
-- LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
-- OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
-- THE SOFTWARE.

return {
    en = {
        getMobileApp = 'Free on your mobile!',
        allCoinsCollected = 'All stars collected!',
        allLevelsCompleted = 'All levels completed!',
        allLevelsCompletedComment = 'But wait, there are still stars to collect...',
        comingSoon1 = 'New season',
        comingSoon2 = 'coming soon!',
        credits_1 = '- Developed By -',
        credits_2 = '- Programming & Design -',
        credits_3 = '- Art & Concept -',
        credits_4 = '- Tools & Engines - ',
        credits_5 = '- Open Source -',
        credits_6 = '- Privacy Policy -',
        credits_7 = '- User Support -',
        credits_8 = '- Special Thanks -',
        credits_9 = '- Sound Effects -',
        credits_10 = '- Original Music -',
        fatal = "We're sorry, something went wrong. Please try again.",
        hideGrid = 'Hide grid',
        lang = 'English',
        level = 'Level',
        moreLevelComingSoon = 'New levels coming soon!',
        newSeason = 'New season unlocked!',
        paused = 'Paused',
        quitPrompt = 'Quit the game?',
        replayAnim = 'Replay animation',
        resetGame = 'Reset game',
        resetWarning = 'Reset the game progression?',
        season_name_1 = 'The Desserts Menu',
        season_name_2 = 'Spicy Meals',
        season_name_3 = 'Tropical Cuisine',
        season_name_4 = 'Cold Buffet',
        showGrid = 'Show grid',
        wellDone = 'Well done!',
        winlabel = 'Level cleared',
    },
    es = {
        getMobileApp = 'Gratis ya en tu móvil!',
        allCoinsCollected = '¡Has conseguido todas las estrellas!',
        allLevelsCompleted = '¡Has acabado todos los niveles!',
        allLevelsCompletedComment = 'Pero aún te falta conseguir todas las estrellas...',
        comingSoon1 = 'Nueva temporada',
        comingSoon2 = 'muy pronto!',
        credits_1 = '- Desarrollado por -',
        credits_2 = '- Programación y Design -',
        credits_3 = '- Graficos y Concepto -',
        credits_4 = '- Herramientas e Engines - ',
        credits_5 = '- Open Source -',
        credits_6 = '- Políticas de privacidad -',
        credits_7 = '- Soporte técnico -',
        credits_8 = '- Agradecimientos -',
        credits_9 = '- Efecto de sonido -',
        credits_10 = '- Música Original -',
        fatal = 'Lo sentimos, algo salió mal. Por favor, intentelo de nuevo.',
        hideGrid = 'Esconder mapa',
        lang = 'Español',
        level = 'Nivel',
        moreLevelComingSoon = 'Nuevos niveles muy pronto!',
        newSeason = '¡Nueva temporada disponible!',
        paused = 'En pausa',
        quitPrompt = '¿Salir del juego?',
        replayAnim = "Volver a ver la animación",
        resetGame = 'Reiniciar',
        resetWarning = 'Reiniciar el juego?',
        season_name_1 = 'Carta De Postres',
        season_name_2 = 'Comida Picante',
        season_name_3 = 'Comida Tropical',
        season_name_4 = 'Bufet Libre',
        showGrid = 'Mostrar mapa',
        wellDone = '¡Felicidades!',
        winlabel = 'Nivel acabado',
    },
    fr = {
        getMobileApp = 'Gratuit pour smartphone!',
        allCoinsCollected = 'Tu as obtenu toutes les étoiles!',
        allLevelsCompleted = 'Tu as complété tous les niveaux!',
        allLevelsCompletedComment = 'Cependant il reste encore des étoiles à récolter...',
        comingSoon1 = 'Nouvelle saison',
        comingSoon2 = 'bientôt disponible!',
        credits_1 = '- Développé par -',
        credits_2 = '- Programmation & Design -',
        credits_3 = '- Graphiques & Concepts -',
        credits_4 = '- Outils & Moteurs de jeu -',
        credits_5 = '- Open Source -',
        credits_6 = '- Politique de confidentialité -',
        credits_7 = '- Support -',
        credits_8 = '- Remerciements -',
        credits_9 = '- Effets sonores -',
        credits_10 = '- Musique Originale -',
        fatal = 'Nous somme désolé mais une erreur est survenue. Veuillez essayer à nouveau.',
        hideGrid = 'Cacher la grille',
        lang = 'Français',
        level = 'Niveau',
        moreLevelComingSoon = 'De nouveaux niveaux bientôt disponibles!',
        newSeason = 'Nouvelle saison débloquée!',
        paused = 'En pause',
        quitPrompt = 'Sortir du jeux?',
        replayAnim = "Revoir l'animation",
        resetGame = 'Réinitialiser',
        resetWarning = 'Réinitialiser le jeux?',
        season_name_1 = 'Carte Des Desserts',
        season_name_2 = 'Des Plats Relevés',
        season_name_3 = 'Cuisine Tropicale',
        season_name_4 = 'Buffet Froid',
        showGrid = 'Montrer la grille',
        wellDone = 'Bien joué!',
        winlabel = 'Niveau fini',
    }
}
