return {
    emitterType = kCCParticleModeGravity, -- kCCParticleModeGravity, kCCParticleModeRadius
    angle = 0.0,
    angleVariance = 360.0,
    duration = -1.0, -- kCCParticleDurationInfinity 
    maxParticules = 20,
    blendFuncSource = GL_SOURCE_ALPHA,
    blendFuncDestination = GL_ONE_MINUS_SRC_ALPHA,
    blendAdditive = false,
    startColor = {0.35,1.0,1.0,0.52},
    startColorVariance = {0,0,0.17,1},
    finishColor = {0.4,1,1,0},
    finishColorVariance = {0,0,0,0},
    startSize = 56.0,
    startSizeVariance = 34.0,
    finishSize = 37.0,
    finishSizeVariance = 0.0,
    lifespan = 0.46,
    lifespanVariance = 0.855,
    rotationStart = 0,
    rotationStartVariance = 0,
    rotationEnd = 0,
    rotationEndVariance = 0,
    sourcePosition = {0,0},
    sourcePositionVariance = {161,7},
    textureFileName = '',
    textureImageData = '',
    -- Mode Radius
    maxRadius = 1.0,
    maxRadiusVariance = 1.0,
    minRadius = 1.0,
    rotatePerSecond = 0.0,
    rotatePerSecondVariance = 0.0,
    -- Mode gravity 
    gravity = {0,0},
    speed = 284.0,
    speedVariance = 0.0,
    radialAcceleration = -380.0,
    radialAccelVariance = 0.0,
    tangentialAcceleration = -144.7,
    tangentialAccelVariance = 0.0,
    -- rotationIsDir = false , -- not supported in Lua
}
