/**
 * Copyright (c) 2012 Laurent Zubiaur - pix2d.com
 *
 * All rights reserved.
 *  
 * This file is automatically generated. Don't edit it manually.
 */ 

#pragma once
#ifndef PIX2D_VERSION_H
#define PIX2D_VERSION_H

#define BUILD_VERSION_MAJOR {}
#define BUILD_VERSION_MINOR {}
#define BUILD_VERSION_REVISION {}
#define BUILD_VERSION_STR "{}"
#define BUILD_VERSION_TAG "{}"
#define BUILD_DATE "{}"

#endif /// PIX2D_VERSION_H
